// src/lib/components/ui/button/button.svelte
<script lang="ts" module>
	import { cva, type VariantProps } from 'class-variance-authority';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	const buttonVariants = cva(
		'inline-flex justify-center text-nowrap items-center cursor-pointer transition-color duration-150 disabled:bg-opacity-50',
		{
			variants: {
				variant: {
					default: 'bg-primary text-primary-fg ring ring-primary hover:bg-primary/80',
					outlined: 'bg-primary/10 ring ring-primary/40 hover:bg-primary/20 hover:ring-primary/70'
				},
				size: {
					default: 'h-10 py-5 px-4',
					sm: 'h-8 py-4 px-2 text-sm',
					lg: 'h-12 py-5 px-8'
				},
				rounded: {
					sm: 'rounded-sm',
					md: 'rounded-md',
					lg: 'rounded-lg'
				}
			},

			defaultVariants: {
				variant: 'default',
				size: 'default'
			}
		}
	);
	export type ButtonVariant = VariantProps<typeof buttonVariants>['variant'];
	export type ButtonSize = VariantProps<typeof buttonVariants>['size'];
	export type ButtonRounded = VariantProps<typeof buttonVariants>['rounded'];

	export type ButtonProps = HTMLButtonAttributes & {
		variant?: ButtonVariant;
		size?: ButtonSize;
		rounded?: ButtonRounded;
	};
</script>

<script lang="ts">
	import { cn } from '$lib/utils';
	let {
		class: className,
		type = 'button',
		variant = 'default',
		size = 'default',
		rounded,
		children,
		...rest
	}: ButtonProps = $props();
</script>

<button class={cn(buttonVariants({ variant, size, rounded, className }))} {...rest}
	>{@render children?.()}</button
>

// src/components/ui/Button.tsx
import type { ReactNode } from "react";

type Props = React.ComponentProps<"button"> & {
  variant?: "default" | "secondary" | "primary" | "destructive" | "ghost";
  size?: "default" | "sm" | "lg" | "icon";
  children: ReactNode;
};

function Button({
  children,
  className,
  variant = "default",
  size = "default",
  ...props
}: Props) {
  let colors = "";
  let sizes = "";
  switch (variant) {
    case "default":
      colors = "bg-foreground text-background hover:bg-foreground/80";
      break;
    case "secondary":
      colors = "bg-secondary text-secondary-foreground hover:bg-secondary/80";
      break;
    case "primary":
      colors = "bg-primary text-primary-foreground hover:bg-primary/80";
      break;
    case "destructive":
      colors =
        "bg-destructive text-secondary dark:text-secondary-foreground hover:bg-destructive/80";
      break;
    case "ghost":
      colors = "border-none hover:scale-110";
      break;
    default:
      colors = "";
  }
  switch (size) {
    case "default":
      sizes = "h-10 px-3";
      break;
    case "sm":
      sizes = "h-9 px-3";
      break;
    case "lg":
      sizes = "h-11 px-4";
      break;
    case "icon":
      sizes = "h-9 w-9 p-1";
      break;
    default:
      sizes = "";
  }
  return (
    <button
      className={`inline-flex justify-center border items-center text-sm font-medium tracking-wide gap-2 whitespace-nowrap rounded ${colors} ${sizes} transition-all duration-200 cursor-pointer disabled:opacity-50 disabled:pointer-events-none disabled:cursor-not-allowed disabled:selection: ${className}`}
      {...props}
    >
      {children}
    </button>
  );
}

export default Button;
